# Generated by Django 2.2.3 on 2020-06-18 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mc', models.IntegerField(blank=True, null=True)),
                ('mtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.MTask')),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Performance')),
                ('userdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.UserDetail')),
            ],
        ),
    ]
