# Generated by Django 2.2.3 on 2020-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillog',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
