# Generated by Django 2.2.3 on 2020-05-30 06:39

import Tech.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCNum', models.IntegerField()),
                ('SCName', models.CharField(blank=True, max_length=100, null=True)),
                ('tcontent', models.TextField(blank=True, null=True)),
                ('fcontent', models.FileField(blank=True, null=True, upload_to='files/')),
                ('bcontent', models.BooleanField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCName', models.CharField(blank=True, max_length=100, null=True)),
                ('filetype', django_enumfield.db.fields.EnumField(blank=True, default=0, enum=Tech.models.FileType, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Department')),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Performance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Performance')),
            ],
        ),
        migrations.CreateModel(
            name='STask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TNum', models.IntegerField()),
                ('DetNum', models.IntegerField(blank=True, null=True)),
                ('SCNum', models.IntegerField(blank=True, null=True)),
                ('TName', models.CharField(max_length=40)),
                ('DetName', models.CharField(blank=True, max_length=40, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('bool', models.BooleanField(blank=True, default=0, null=True)),
                ('Dbool', models.BooleanField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TNum', models.IntegerField()),
                ('DetNum', models.IntegerField(blank=True, null=True)),
                ('SCNum', models.IntegerField(blank=True, null=True)),
                ('TName', models.CharField(max_length=40)),
                ('DetName', models.CharField(blank=True, max_length=40, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=Tech.models.statustyle)),
                ('place', models.TextField(blank=True, null=True)),
                ('bool', models.BooleanField(blank=True, default=0, null=True)),
                ('Dbool', models.BooleanField(blank=True, default=0, null=True)),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Department')),
                ('mcontents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.MContents')),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Performance')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Team')),
                ('userdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.UserDetail')),
                ('workname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.WorkName')),
            ],
        ),
        migrations.AddField(
            model_name='mcontents',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Performance'),
        ),
        migrations.CreateModel(
            name='DetailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now_add=True, null=True)),
                ('mod', models.TextField(blank=True, null=True)),
                ('mtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.MTask')),
                ('userdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.UserDetail')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tech.Performance'),
        ),
    ]
