# Generated by Django 2.2.3 on 2020-05-31 21:38

import Tech.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcontents',
            name='filetype',
            field=django_enumfield.db.fields.EnumField(blank=True, default=0, enum=Tech.models.FileType, null=True),
        ),
    ]
