# Generated by Django 2.2.3 on 2020-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtask',
            name='Dbool',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stask',
            name='Dbool',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mtask',
            name='DetName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mtask',
            name='DetNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stask',
            name='DetName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='stask',
            name='DetNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
