# Generated by Django 3.0.5 on 2020-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0002_auto_20200526_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask',
            name='SCNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
