# Generated by Django 3.0.5 on 2020-05-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0003_auto_20200526_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeCrTem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('direction', models.TextField(blank=True, null=True)),
                ('construct', models.TextField(blank=True, null=True)),
                ('check', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mcontents',
            name='SCName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scontents',
            name='SCName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
