# Generated by Django 3.0.5 on 2020-05-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0004_auto_20200527_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtask',
            name='SCNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtask',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtask',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
