# Generated by Django 3.0.5 on 2020-05-27 17:30

import Tech.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0005_auto_20200528_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtask',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=Tech.models.statustyle),
        ),
    ]
